#!/usr/bin/env bash

SOURCE=$(curl -sS "https://raw.githubusercontent.com/arkenfox/user.js/master/user.js")
echo "### autogenerated"
echo "### SEE https://github.com/arkenfox/user.js"
echo "{"
echo "$SOURCE" \
  | grep "user_pref" \
  | grep -v "^\s*//" \
  | grep -v "_user.js.parrot" \
  | sed -E 's/^user_pref\((".+"),\s*(.+)\).*$/  \1 = \2;/g'
echo "}"
